### ISSUE TITLE
Error not found

### ISSUE THREAD

**Issue by Rudy-Perrin** [pulkitgangwar/nextjs-app-directory-commands#5]
Doesn't work when execute "Page: (generate page in app directory)" or Flowchart: (generate app directory flow chart) command return :
Command 'nextjs-app-directory-commands.page' not found or command 'nextjs-app-directory-commands.flowchart' not found.

![Capture d’écran 2023-06-05 215129](https://github.com/pulkitgangwar/nextjs-app-directory-commands/assets/15348015/9a2269d8-446f-4095-82ed-1504d8632793)

**Comment by ben2613** [comment]
Not sure if the same cause, I got this error message in my console

Activating extension 'PulkitGangwar.nextjs-app-directory-commands' failed: ENOENT: no such file or directory, open 'C:\c:\Users\XXXX\Documents\git\XXXX\package.json'.

Seems a extra c:\ is in the path

**Comment by ben2613** [comment]
```ts
const packageJson = await promisedFs.readFile(file.fsPath, {
  encoding: "utf8",
});
```

```ts
project.rootPath = file.fsPath.split(/[\\/]package.json/)[0]; // as getAppDirectoryPath is using fs too
```
After changing file.path to file.fsPath and modify the split pattern this I am able to use the command to generate page

but still not able to generate the flowchart, I guess there are some other OS-related path issues

**Comment by pulkitgangwar** [comment]
I'm sorry for the late response. I've just pushed a new update to the repository that should resolve the problem. Please let me know if you're still having any issues.
